import project from './project'
import review from './review'
import faq from './faq'
import siteSettings from './siteSettings'
import page from './page'
import redirect from './redirect'
import navigation from './navigation'
import pageMeta from './pageMeta'
import homeCopy from './homeCopy'
import sharedCopy from './sharedCopy'
import aboutCopy from './aboutCopy'
import serviceCopy from './serviceCopy'
import carouselPhotos from './carouselPhotos'

export const schemaTypes = [project, review, faq, siteSettings, page, redirect, navigation, pageMeta, homeCopy, sharedCopy, aboutCopy, serviceCopy, carouselPhotos]
